name: MSBuild

on:
  push:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: MakeshiftSDK.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run Premake
      run: scripts/generateProject_VisualStudio22

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Read current version
      id: set-version
      run: |
        VERSION=$(grep -oP '(?<=VERSION ")[^"]*' MakeshiftEngine/src/Makeshift/Version.h)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Increment COMMITHASH
      run: echo "COMMITHASH=$(date +%s)" >> $GITHUB_ENV

    - name: Update Version and Commit Hash
      run: |
        sed -i "s/COMMIT \".*\"/COMMIT \"$(cat $GITHUB_ENV | grep -oP 'COMMITHASH=\K.*')\"/" MakeshiftEngine/src/Makeshift/Version.h
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add MakeshiftEngine/src/Makeshift/Version.h
        git add path/to/your/second/file.extension
        git commit -m "Update VERSION and COMMIT" Version.h path/to/your/second/file.extension

    - name: Create Editor Artifact
      uses: actions/upload-artifact@v2
      with:
        name: editor-artifact
        path: out/bin/Release-window-x86_64/MakeshiftEditor  

    - name: Create App Artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-artifact
        path: out/bin/Release-window-x86_64/MakeshiftApplication

    - name: Create GitHub Release
      run: |
        echo "Creating GitHub release..."
        RELEASE_TITLE="Release v${{ env.VERSION }}${{ env.COMMITHASH }}"
        gh release create "$RELEASE_TITLE" \
          --notes "Release notes for $RELEASE_TITLE" \
          --repo MindlessTeam/Makeshift \
          app-artifact editor-artifact
